### ISSUE TITLE
tutorial installation

### ISSUE THREAD

**Issue by sofwarestore** [jzolee/HAL2UDP#3]
i have try install but i get error this
https://drive.google.com/file/d/1lIcT0Yi34sxzRCUfmFuPRTwbWqgHbC6g/view?usp=drive_link

before i already have linuxcnc but with lpt port..so i want to add esp32 but i got error like picture..is there any suggestion

**Comment by jzolee** [comment]
> i have try install but i get error this https://drive.google.com/file/d/1lIcT0Yi34sxzRCUfmFuPRTwbWqgHbC6g/view?usp=drive_link
> 
> before i already have linuxcnc but with lpt port..so i want to add esp32 but i got error like picture..is there any suggestion

I removed the confusing lines in the udp2.ini file - I hope I found them all. I'm sorry, but I uploaded my own config file, which contains useless stuff for others.

**Comment by sofwarestore** [comment]
i still get error this

https://drive.google.com/file/d/1OFOUGBFV6qgJI5Y66VLqsO5w3HodtxRl/view?usp=sharing

but i already can run the program..is it all right to ignore the error
